POST https://localhost:7283/cars/create
Content-Type: application/json

{
    "brand": "Toyota",
    "model": "2020",
    "state": "Available",
    "type": "4x4",
    "startDateTime": "2024-02-08T08:00:00"
}